from piece_class import piece; pieces = []; pieces.append(piece('Still Life with a Ginger Jar and Eggplants', 'Paul Cézanne', '1893-94'))
pieces.append(piece('New York City Ⅰ', 'Piet Mondrian', '1942'))
pieces.append(piece('Girl Before a Mirror', 'Pablo Picasso', '1932'))
pieces.append(piece('Oath of the Horatii', 'Jacques-Louis David', '1784'))
pieces.append(piece('Watson and the Shark', 'John Singleton Copley', '1778'))
pieces.append(piece('La Grande Odalisque', 'Jean Auguste Dominique Ingres', '1814'))
pieces.append(piece('La Comtesse d\'Haussonville', 'Jean Auguste Dominique Ingres', '1845'))
pieces.append(piece('The Raft of the Medusa', 'Théodore Géricault', '1818-19'))
pieces.append(piece('Liberty Leading the People', 'Eugène Delacroix', '1830'))
pieces.append(piece('Still Life with a Lobster', 'Eugène Delacroix', '1827'))
pieces.append(piece('The Stone Breakers', 'Gustave Courbet', '1849'))
pieces.append(piece('The Third-Class Carriage', 'Honoré Daumier', '1862'))
pieces.append(piece('Galloping Horse', 'Eadweard Muybridge', '1878'))
pieces.append(piece('Déjeuner sur L\'Herbe (Luncheon on the Grass)', 'Édouard Manet', '1863'))
pieces.append(piece('Impression- Sunrise', 'Claude Monet', '1872'))
pieces.append(piece('Rouen Cathedral', 'Claude Monet', '1894'))
pieces.append(piece('Where do we come from? What are we? Where are we going?', 'Paul Gauguin', '1897'))
pieces.append(piece('The Glass of Absinth', 'Edgar Dégas', '1876'))
pieces.append(piece('The Little 14-year-old Dancer', 'Edgar Dégas', '1878-81'))
pieces.append(piece('Le Moulin de la Galette', 'Pierre Auguste Renoir', '1876'))
pieces.append(piece('Girl with a Watering Can', 'Pierre Auguste Renoir', '1876'))
pieces.append(piece('The Starry Night', 'Vincent van Gogh', '1889'))
pieces.append(piece('Sunday Afternoon on the Island of La Grande Jatte', 'Georges Seurat', '1884-86'))
pieces.append(piece('The Night Café', 'Vincent van Gogh', '1888'))
pieces.append(piece('Mont Sainte-Victoire', 'Paul Cézanne', '1902-04'))
pieces.append(piece('Woman with a Hat', 'Henri Matisse', '1905'))
pieces.append(piece('Portrait of Madame Matisse (The Green Stripe)', 'Henri Matisse', '1905'))
pieces.append(piece('The Dessert- Harmony in Red', 'Henri Matisse', '1908'))
pieces.append(piece('Les Demoiselles d\'Avignon', 'Pablo Picasso', '1907'))
pieces.append(piece('Girl with Mandolin', 'Pablo Picasso', '1910'))
pieces.append(piece('The City', 'Fernand Léger', '1919'))
pieces.append(piece('Nude Descending a Staircase (No. 2)', 'Marcel Duchamp', '1912'))
pieces.append(piece('Still Life with Chair Caning', 'Pablo Picasso', '1912'))
#pieces.append(piece('', '', ''))

remove = [1,2,3,4,5,9,10,11,12,13,15,18,19,21,22,24,26,27,30,31,32,33]

for i in range(len(pieces)-1,-1,-1):
    if (i + 1) in remove:
        pieces.pop(i)